### PR TITLE
Fix MavenArtifactResolver issues with maven 3.9+

### LINKED ISSUE #506: Support for Maven 3.9.0 or newer
Currently support for Maven is limited to v3.8.8, but it's getting increasingly more difficult to support that in local build environments.  For example, Homebrew formulas force upgrades well past 3.9.0 for maven now.

### PR DESCRIPTION
**Pull request by jperedadnr**
Fixes #506, by removing unnecessary and deprecated way of getting an instance of a `RepositorySystem`, and a `RepositorySession`, by just getting these injected by Maven itself in the base Mojo.

Many dependencies from org.eclipse.aether/org.apache.maven.resolver are removed in the process, and therefore, the `org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory` [missing class](https://github.com/gluonhq/gluonfx-maven-plugin/issues/458#issuecomment-1462035876) from maven-core is not needed anymore.

Now, the plugin can run with any version up until 3.9.9 (latest before going to Maven 4, which is still in beta)

### CODE REVIEW

File: src/main/java/com/gluonhq/NativeBaseMojo.java [hunk 1]
```diff
@@ -74,14 +77,31 @@ public abstract class NativeBaseMojo extends AbstractMojo {
 
     private static final List<String> ALLOWED_DEPENDENCY_TYPES = Collections.singletonList("jar");
 
-    // TODO: Remove this restriction when MavenArtifactResolver works with Maven 3.9.0+
-    private static final Version MAX_SUPPORTED_MAVEN_VERSION = new Version(3, 8, 8);
+    private static final Version MAX_SUPPORTED_MAVEN_VERSION = new Version(3, 9, 9);
```
Comment (johanvos) [inline src/main/java/com/gluonhq/NativeBaseMojo.java:80]: Do we expect this not to work on 4?

Comment (jperedadnr) [reply src/main/java/com/gluonhq/NativeBaseMojo.java:80]: I haven't tested it yet, honestly. Many parts are moving and being deprecated/removed for Maven 4, so I'd say we'll need to revisited when people start to use it (beta for now), or it gets finally released.

Comment (tiainen) [reply src/main/java/com/gluonhq/NativeBaseMojo.java:80]: I believe we need to change at least some logic here, because at this point, the plugin won't work starting with maven 3.9.10. We can perhaps invert the logic and say that we support all versions up to 4.0.0 (but not inclusive)?

File: src/main/java/com/gluonhq/utils/MavenArtifactResolver.java [hunk 2]
```diff
@@ -98,77 +81,24 @@ public static MavenArtifactResolver getInstance() {
...
+        this.remoteRepositories = repositories;
     }
 
     /**
      * Creates and initializes a new instance with a list of remote
      * repositories, only if such instance doesn't already exist
      *
-     * @param repositories a list of remote repositories
+     * @param repositorySystem The entry point to Maven Artifact Resolver
+     * @param systemSession The current repository/network configuration of Maven
```
[the remark this answers is not in the document]
Comment (jperedadnr) [reply src/main/java/com/gluonhq/utils/MavenArtifactResolver.java:95]: good catch, fixed

File: src/main/java/com/gluonhq/NativeBaseMojo.java (hunk 1 above)
Comment (jperedadnr) [reply src/main/java/com/gluonhq/NativeBaseMojo.java:80]: Maven 4.0.0 is not released yet, but I'm trying to test Maven 4.0.0-alpha-13, and `new Version()` fails to parse it.

Removing the whole version check works (I've tested 3.6.3, 3.8.1, 3.8.8, 3.9.0, 3.9.9, 4.0.0-alpha-13), so we don't need it anymore.

**Review by tiainen — APPROVED** [review]
